version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # porta AMQP
      - "15672:15672"    # UI web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Cashflow.Operations.Api/Dockerfile
    container_name: cashflow-api
    ports:
      - "5000:8080"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
      - Rabbit__Host=rabbitmq
      - Rabbit__Port=5672
      - Rabbit__UserName=guest
      - Rabbit__Password=guest

  worker:
    build:
      context: .
      dockerfile: Cashflow.Consolidation.Worker/Dockerfile
    container_name: cashflow-worker
    depends_on:
      - rabbitmq
    environment:
      - Rabbit__Host=rabbitmq
      - Rabbit__Port=5672
      - Rabbit__UserName=guest
      - Rabbit__Password=guest
